name: Plugin build and publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [14]
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Update apt
        run: sudo apt update
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fast install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload built plugin
        uses: actions/upload-artifact@v2
        with:
          name: Plugin
          path: |
            dist/
            package.json
